-- CASO: EMPRESA GLOBAL
-- Con operaciones en varias regiones


----------------------------------
-- 1. CREACION DE TBS
----------------------------------

CREATE TABLESPACE TBS_ASIA
DATAFILE 'E:\TEMP\DF_COMPROBANTES_ASIA.DBF'
SIZE 10M;

CREATE TABLESPACE TBS_EUROPA
DATAFILE 'E:\TEMP\DF_COMPROBANTES_EUROPA.DBF'
SIZE 10M;

CREATE TABLESPACE TBS_AL
DATAFILE 'E:\TEMP\DF_COMPROBANTES_AL.DBF'
SIZE 10M;
  
CREATE TABLESPACE TBS_OTROS
DATAFILE 'E:\TEMP\DF_COMPROBANTES_OTROS.DBF'
SIZE 10M;

-- Tablespaces
SELECT TABLESPACE_NAME "TABLESPACE"	
FROM DBA_TABLESPACES 
ORDER BY 1;

-- Espacio Total en MB
SELECT 
	tablespace_name,
	round(sum(BYTES/1024/1024),0) ESPACIO_MB
FROM dba_data_files b
GROUP BY b.tablespace_name
ORDER BY 1;

-- Espacio libre en MB
SELECT 
	tablespace_name,
	ROUND(sum(BYTES/1024/1024),0) ESPACIO
FROM dba_free_space
GROUP BY tablespace_name
ORDER BY 1;



----------------------------------
-- 2. TABLA PARTICIONADA POR LISTA
----------------------------------

CREATE TABLE EUREKA.Ventas(
	ID NUMBER(10),
	ORIGEN VARCHAR2(20),
	FECHA DATE default sysdate 
)
PARTITION BY LIST( ORIGEN)
(
	PARTITION ventas_ASIA  VALUES('ASIA')     tablespace TBS_ASIA,
	PARTITION ventas_EUROPA VALUES ('EUROPA') tablespace TBS_EUROPA,
	PARTITION ventas_AL     VALUES ('AL')     tablespace TBS_AL,
	PARTITION ventas_otros  VALUES(DEFAULT)   tablespace TBS_OTROS 
);


-------------------------------------------------
-- 3 INSERTANDO DATOS EN TABLAS PARTICIONADAS
-------------------------------------------------

INSERT INTO VENTAS
SELECT LEVEL, 'ASIA', SYSDATE
FROM DUAL CONNECT BY LEVEL <= 100000;
 
INSERT INTO VENTAS
SELECT LEVEL, 'EUROPA', SYSDATE
FROM DUAL CONNECT BY LEVEL <= 100000;


-------------------------------------------------
-- 4 QUERY DE TABLAS PARTICIONADAS
-------------------------------------------------

SELECT * FROM VENTAS;

SELECT * FROM VENTAS PARTITION ( ventas_ASIA );
 
SELECT * FROM VENTAS PARTITION (ventas_EUROPA);


----------------------------------
-- 5 CONSULTANDO TABLAS PARTICIONADAS
----------------------------------
SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'VENTAS' ;



----------------------------------
-- 6 COMPARANDO PLANES DE EJECUCION 
--   ENTRE TABLA PARTICIONADA Y REGULAR
----------------------------------

CREATE TABLE VENTASREGULAR(
	ID NUMBER(10),
	ORIGEN VARCHAR2(20),
	FECHA DATE default sysdate 
);

INSERT INTO VENTASREGULAR
SELECT LEVEL, 'ASIA', SYSDATE
FROM DUAL CONNECT BY LEVEL <= 100000;
 
INSERT INTO VENTASREGULAR
SELECT LEVEL, 'EUROPA', SYSDATE
FROM DUAL CONNECT BY LEVEL <= 100000;


---- PLAN DE EJECUCION TABLA REGULAR
EXPLAIN PLAN 
FOR
SELECT * FROM VENTASREGULAR
WHERE ORIGEN = 'ASIA';

SELECT * FROM TABLE( DBMS_XPLAN.DISPLAY );

---- PLAN DE EJECUCION TABLA PARTICIONADA
EXPLAIN PLAN 
FOR
SELECT * FROM VENTAS PARTITION ( VENTAS_ASIA )
WHERE ORIGEN = 'ASIA';

SELECT * FROM TABLE( DBMS_XPLAN.DISPLAY )


SELECT COUNT(*) FROM VENTAS;  

SELECT COUNT(*) FROM VENTASREGULAR; 



